[package]
name = "nakama-rs"
version = "0.1.0"
authors = ["Fedor Logachev <not.fl3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
nanoserde = "0.1"

quad-net = { git = "https://github.com/not-fl3/quad-net.git" }
